#!/bin/env bash
set -eox pipefail
DIR="$(dirname "$(readlink -f "$0")")"

log() {
  msg="$1"
  echo "********************************************"
  echo "$msg"
  echo "********************************************"
  echo ""
}

echo "Swap stable/bookworm for testing in /etc/apt/sources.list"
echo "Please enter 'testing' when you're done..."

while true; do
    # Read user input without displaying it
    read -r input

    # Check if input matches required string
    if [ "$input" == "testing" ]; then
        echo "Correct input received! Continuing..."
        break
    fi
done

sudo apt update
sudo apt upgrade
sudo apt install sudo-rs

sudo-rs apt remove -y \
  firefox-esr \
  aisleriot \
  five-or-more \
  four-in-a-row \
  gnome-2048 \
  gnome-chess \
  hoichess \
  gnome-klotski \
  gnome-mines \
  gnome-nibbles \
  gnome-robots \
  gnome-mahjongg \
  gnome-sudoku \
  gnome-taquin \
  gnome-tetravex \
  hitori \
  lightsoff \
  libreoffice-calc \
  libreoffice-draw \
  libreoffice-impress \
  libreoffice-writer \
  quadrapassel \
  swell-foop \
  tali

echo "Disabling sleeping via dconf"
dconf write /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type "'nothing'"

sudo-rs apt install -y \
  apt-transport-https \
  autoconf \
  autopoint \
  bison \
  build-essential \
  cmake \
  clang \
  clang-tidy \
  clang-format \
  curl \
  exuberant-ctags \
  fish \
  git \
  git-doc \
  git-gui \
  git-svn \
  gitg \
  gnome-calculator \
  gnome-clocks \
  gnome-weather \
  htop \
  imagemagick \
  inotify-tools \
  jq \
  libbz2-dev \
  libclang-dev libffi-dev \
  libfontconfig1-dev \
  libfreetype6-dev \
  libgdbm-dev \
  libgtk-3-dev \
  libncurses5-dev \
  libreadline-dev \
  libsensors-dev \
  libssl-dev \
  libtool \
  libxcb-xfixes0-dev \
  libxml2-dev \
  libxslt1-dev \
  libyaml-dev \
  lm-sensors \
  nautilus \
  pandoc \
  parallel \
  pkg-config \
  pspg \
  zlib1g-dev

log "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:jc00ke/dotfiles.git"


log "Install nix"
sh <(curl -L https://nixos.org/nix/install) --no-daemon

chsh -s /usr/bin/fish

mkdir -p "$HOME/projects"
mkdir -p "$HOME/src"
cd "$HOME" || exit

log "Setting up firefox"
sudo-rs install -d -m 0755 /etc/apt/keyrings
wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo-rs tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null
expected_fingerprint="35BAA0B33E9EB396F59CA838C0BA5CE6DC6315A3"
actual_fingerprint="$(gpg -n -q --import --import-options import-show /etc/apt/keyrings/packages.mozilla.org.asc | awk '/pub/{getline; gsub(/^ +| +$/,""); print $0}')"
if [ "$actual_fingerprint" != "$expected_fingerprint" ]; then
  echo "Firefox fingerprint doesn't match!"
  echo "Actual:   $actual_fingerprint"
  echo "Expected: $expected_fingerprint"
  exit 1
fi
echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo-rs tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null
echo '
Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000
' | sudo-rs tee /etc/apt/preferences.d/mozilla

log "Setting up 1Password"
curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo-rs gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main' | sudo-rs tee /etc/apt/sources.list.d/1password.list
sudo-rs mkdir -p /etc/debsig/policies/AC2D62742012EA22/
curl -sS https://downloads.1password.com/linux/debian/debsig/1password.pol | sudo-rs tee /etc/debsig/policies/AC2D62742012EA22/1password.pol
sudo-rs mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
curl -sS https://downloads.1password.com/linux/keys/1password.asc | sudo-rs gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg

log "Setting up gh CLI"
curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo-rs dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
  && sudo-rs chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
  | sudo-rs tee /etc/apt/sources.list.d/github-cli.list > /dev/null

log "Setting up mise"
wget https://github.com/cargo-bins/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-musl.tgz
tar xf cargo-binstall-x86_64-unknown-linux-musl.tgz
mv cargo-binstall "$HOME/.local/bin/"
rm cargo-binstall-x86_64-unknown-linux-musl.tgz
wget -qO - https://mise.jdx.dev/gpg-key.pub | gpg --dearmor | sudo-rs tee /etc/apt/keyrings/mise-archive-keyring.gpg 1> /dev/null
echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=amd64] https://mise.jdx.dev/deb stable main" | sudo-rs tee /etc/apt/sources.list.d/mise.list


log "Setting up signal"
wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > signal-desktop-keyring.gpg
cat signal-desktop-keyring.gpg | sudo-rs tee /usr/share/keyrings/signal-desktop-keyring.gpg > /dev/null

echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main' | sudo-rs tee /etc/apt/sources.list.d/signal-xenial.list

log "Setting up Heroku"

log "Add heroku repository to apt"
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/heroku-keyring.gpg] https://cli-assets.heroku.com/channels/stable/apt ./" | sudo-rs tee /etc/apt/sources.list.d/heroku.list

log "Install heroku's release key for package verification"
curl -s https://cli-assets.heroku.com/channels/stable/apt/release.key | gpg --dearmor | sudo-rs tee /usr/share/keyrings/heroku-keyring.gpg > /dev/null

log "Install tailscale"
curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg | sudo-rs tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
curl -fsSL https://pkgs.tailscale.com/stable/debian/bookworm.tailscale-keyring.list | sudo-rs tee /etc/apt/sources.list.d/tailscale.list

sudo-rs apt update && sudo-rs apt install firefox 1password 1password-cli gh mise signal-desktop-beta heroku tailscale -y

log "Install home-manager in a new terminal"
echo "nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager"
echo "nix-channel --update"
echo "nix-shell '<home-manager>' -A install"
