[tools]
bat = "0.23.0"
delta = "0.15.1"
deno = "1.26.2"
difftastic = "0.36.1"
direnv = "2.32.2"
duf = "0.8.1"
elixir = "1.15.4-otp-25"
elm = "0.19.1"
erlang = "25.3.2.1"
fd = "8.7.0"
fzf = "0.42.0"
jless = "0.7.1"
lua = "5.4.2"
neovim = "0.9.1"
nodejs = "18.11.0"
postgres = "15.2"
python = "3.10.2"
redis = "6.2.3"
ripgrep = "13.0.0"
ruby = "3.1.2"
rust = "1.70.0"
shellcheck = "0.8.0"
shellspec = "0.28.1"
shfmt = "3.4.3"
starship = "1.11.0"
steampipe = "0.20.0-test.1"
stylua = "0.13.0"
yq = "4.27.5"
zoxide = "0.9.1"
sqlite = "latest"
eza = "0.11.0"
node = "20.6.0"
