[tools]
bat = "0.23.0"
delta = "0.15.1"
deno = "1.26.2"
difftastic = "0.36.1"
direnv = "2.32.2"
duf = "0.8.1"
elixir = "1.15.4-otp-25"
erlang = "25.3.2.1"
fd = "8.7.0"
fzf = "0.42.0"
jless = "0.7.1"
lua = "5.4.2"
neovim = "0.9.4"
python = "3.10.2"
ripgrep = "13.0.0"
ruby = "3.1.2"
rust = "1.73.0"
shellcheck = "0.8.0"
shellspec = "0.28.1"
shfmt = "3.4.3"
starship = "1.16.0"
steampipe = "0.21.1"
stylua = "0.13.0"
yq = "4.27.5"
zoxide = "0.9.1"
eza = "0.15.1"
node = "20.6.0"
fx = "30.2.0"
aws-vault = "7.2.0"
