version: 2

tools:
  mix_credo: &mix_credo
    lint-command: |
      MIX_ENV=test \
      mix credo suggest \
      --format=flycheck \
      --read-from-stdin \
      ${INPUT}
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %t: %m'
      - '%f:%l: %t: %m'
    root-markers:
      - mix.lock
      - mix.exs

  lua-lua-format: &lua-lua-format
    format-command: 'lua-format -i --indent-width=2'
    format-stdin: true

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-source: 'shellcheck'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  sh-shfmt: &sh-shfmt
    format-command: 'shfmt -ci -s -bn'
    format-stdin: true

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

  tailwind-class-sort: &tailwind-class-sort
    format-command: 'rustywind --stdin'
    format-stdin: true

languages:
  elixir:
    - <<: *mix_credo
  html:
    - <<: *tailwind-class-sort
  lua:
    - <<: *lua-lua-format
  sh:
    - <<: *sh-shellcheck
    - <<: *sh-shfmt
  yaml:
    - <<: *yaml-yamllint
