version: 2
log-file: /home/jesse/.efm-langserver.log
log-level: 1
tools:
  mix_credo: &mix_credo
    lint-command: |
      MIX_ENV=test \
      mix credo suggest \
      --format=flycheck \
      --read-from-stdin \
      ${INPUT}
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %t: %m'
      - '%f:%l: %t: %m'
    root-markers:
      - mix.lock
      - mix.exs
  lua-stylua: &lua-stylua
    format-command: stylua --indent-type=Spaces --indent-width=2 --column-width=110 -
    format-stdin: true
  sh-shellcheck: &sh-shellcheck
    lint-command: shellcheck -f gcc -x
    lint-source: shellcheck
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'
  sh-shfmt: &sh-shfmt
    format-command: altshfmt -ci -s -i 2 -bn
    format-stdin: true
  yaml-cfn-lint: &yaml-cfn-lint
    # https://vim-jp.org/vimdoc-en/quickfix.html#error-file-format
    # https://github.com/reviewdog/errorformat
    lint-command: |
      cfn-lint \
      -f parseable \
      ${INPUT} \
      | awk \
      '{ split($0,a,":"); print a[1] ":" a[2] ":" a[3] ":" a[6] ":" a[7] }'
    lint-formats:
      - '%f:%l:%c:%n:%m'
    lint-stdin: true
  yaml-yamllint: &yaml-yamllint
    lint-command: yamllint -f parsable -
    lint-stdin: true
    format-command: yq e -P -M
    format-stdin: true
  tailwind-class-sort: &tailwind-class-sort
    format-command: rustywind --stdin
    format-stdin: true
languages:
  elixir:
    - !!merge <<: *mix_credo
  html:
    - !!merge <<: *tailwind-class-sort
  lua:
    - !!merge <<: *lua-stylua
  sh:
    - !!merge <<: *sh-shellcheck
    - !!merge <<: *sh-shfmt
  yaml:
    #- !!merge <<: *yaml-cfn-lint
    - !!merge <<: *yaml-yamllint
