# /etc/regolith/i3status-rust/config.toml
[theme]
theme = "semi-native"

[icons]
icons = "awesome4"

[[block]]
block = "net"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "cpu"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "battery"
format = " $icon\u2009 $percentage "
missing_format = ""
device = "DisplayDevice"
driver = "upower"

[[block]]
block = "rofication"
interval = 1
socket_path = "/tmp/rofi_notification_daemon"
[[block.click]]
button = "left"
cmd = "ilia -p notifications"

[[block]]
block = "sound"
driver = "pulseaudio"

[[block.click]]
button = "left"
cmd = "regolith-control-center sound"

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"
show_volume_when_muted = true
max_vol = 100

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %Y-%m-%d %R') "
