set wildignore=*/.git/*
set wildignore+=*/tmp/*
set wildignore+=*.swp
set wildignore+=*/.DS_Store
set wildignore+=*/vendor
set wildignore+=*/env/*
set wildignore+=*/deps/* " Elixir deps
set wildignore+=*/_build/* " Elixir builds
set wildignore+=*/elixir_ls/* " Elixir language server files
set wildignore+=*/node_modules/*
set wildignore+=*/elm-stuff/*
set wildignore+=*/staticfiles/*
set wildignore+=*.gch
set wildignore+=*.o
set wildignore+=*.crdownload
