[settings]
experimental = true
always_keep_download = true
always_keep_install = true
minimum_release_age = "7d"
lockfile = true

[settings.github]
credential_command = 'op read --account my.1password.com "op://Private/GitHub/Tokens/mise-RO"'

[tools]
"aqua:ajeetdsouza/zoxide" = "latest"
"github:sharkdp/bat" = "latest"
"github:sharkdp/fd" = "latest"
neovim = "0.12.4"
tree-sitter = "latest"
