[settings]
experimental = true
always_keep_download = true
always_keep_install = true

[tools]
"aqua:ajeetdsouza/zoxide" = "latest"
"github:sharkdp/bat" = "latest"
"github:sharkdp/fd" = "latest"
neovim = "0.12.2"
tree-sitter = "latest"
