[env]
POSTGRES_EXTRA_CONFIGURE_OPTIONS = "--with-uuid=e2fs --with-openssl"

[tools]
age = "latest"
atuin = "latest"
cargo-binstall = "latest"
cosign = "latest"
duckdb = "latest"
elixir = "1.19.5-otp-28"
erlang = "29.0"
eza = "latest"
fzf = "latest"
gh = "latest"
glab = "latest"
go = "1.26.3"
lua = "5.4.7"
node = "latest"
powershell = "latest"
python = "3.14.5"
ripgrep = "latest"
shellcheck = "latest"
shellspec = "latest"
sqlite = "latest"
starship = "latest"
stylua = "latest"
usage = "latest"

"cargo:b3sum" = "latest"
"github:mvdan/sh" = "latest"
"github:tailwindlabs/tailwindcss" = "latest"
