[env]
POSTGRES_EXTRA_CONFIGURE_OPTIONS = "--with-uuid=e2fs --with-openssl"

[tools]
age = "latest"
atuin = "latest"
cargo-binstall = "latest"
cosign = "latest"
duckdb = "latest"
elixir = "1.19.5-otp-28"
erlang = "28.4"
eza = "latest"
fzf = "latest"
gh = "latest"
glab = "latest"
go = "1.24.0"
lua = "5.4.7"
node = "latest"
python = "3.13.1"
ripgrep = "latest"
shellcheck = "latest"
shellspec = "latest"
sqlite = "latest"
starship = "latest"
stylua = "latest"
usage = "latest"
yq = "latest"

"aqua:mvdan/sh" = "latest"
"cargo:b3sum" = "latest"
"github:tailwindlabs/tailwindcss" = "latest"
